language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
- chmod +x gradlew
- wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip --quiet
- unzip -q android-ndk-r20-linux-x86_64.zip -d $HOME
- export ANDROID_NDK_HOME=$HOME/android-ndk-20
- export PATH=$PATH:$ANDROID_NDK_HOME
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

install:
before_script:
- rm -fr $HOME/.gradle/caches/modules-2/files-2.1/com.bitmark.sdk
- mkdir -p distribution && touch distribution/release_note.txt && touch distribution/all.txt && touch distribution/testers.txt
- touch version.properties && touch key.properties && touch app/fabric.properties && touch sentry.properties && touch app/src/main/resources/sentry.properties
- echo -n >local.properties && echo "ndk.dir=$ANDROID_NDK_HOME"$'\n'"sdk.dir=$ANDROID_HOME" >local.properties
- echo -n >key.properties && echo "api.key.bitmark=$BM_API_KEY"$'\n'"api.key.intercom=$INTERCOM_API_KEY" >key.properties
- echo -n >distribution/release_note.txt && echo "Git commit:$TRAVIS_COMMIT"$'\n'"Message:$TRAVIS_COMMIT_MESSAGE" >distribution/release_note.txt
- echo -n >distribution/testers.txt && echo "$TESTER_EMAIL"
- echo -n >sentry.properties && echo "defaults.project=bitmark-registry"$'\n'"defaults.org=bitmark-inc"$'\n'"auth.token=$SENTRY_AUTH_TOKEN" >sentry.properties
- echo -n >app/fabric.properties && echo "apiSecret=$FABRIC_SECRET"$'\n'"apiKey=$FABRIC_API_KEY" >app/fabric.properties
- echo -n >app/src/main/resources/sentry.properties && echo "dsn=$SENTRY_DSN"$'\n'"buffer.dir=sentry-events"$'\n'"buffer.size=100"$'\n'"async=true"$'\n'"async.queuesize=100" >app/src/main/resources/sentry.properties

script:
- ./gradlew clean fillSecretKey assembleInhouseDebug crashlyticsUploadDistributionInhouseDebug